package com.poshan.entity;


public enum BoxType {

    BOX_2KG,
    PET_JAR_5_LBS_R,

    PET_JAR_5_LBS_BS,

    PET_JAR_2_LBS_J,

    PET_1100ML_JAR,

    PET_88MM_850ML_JAR,

    PET_JAR_5_LBS_M,

    PET_JAR_2_LBS_B,

    PLASTIC_535ML_L_CART_BOTTLE,

    I_SEAL_372MM_HDPE_ONE,

    PLASTIC_325ML_CYLINDRICAL_JAR_WO_CAP,

    PLASTIC_MET_60MM_GOLDEN_CAP,

    PET_275CC_R_TAB_JAR_WITH_PEAL_CAP,

    I_SEAL_877MM_PET_ONE,

    PLASTIC_55_KGS_JAR_300,

    I_SEAL_118MM_PET_ONE,

    I_SEAL_118MM_HDPE_ONE,

    I_SEAL_436MM_PET_ONE,

    PET_46_240ML_SQ_TAB_JAR_H_LOCK,

    PLASTIC_6_KG_JAR,

    PLASTIC_275_KG_JAR,

    PLASTIC_12_KG_JAR_SQ_520,

    PLASTIC_6_KG_JAR_WO_CAP,

    PLASTIC_275_KG_JAR_WO_CAP,

    PLASTIC_88MM_975ML_JAR_WO_CAP,

    PLASTIC_88MM_700ML_HDPE_JAR_WO_CAP,

    PLASTIC_MET_120MM_GOLDEN_CAP,

    PLASTIC_MET_88MM_GOLDEN_CAP,

    PLASTIC_88MM_975ML_JAR;
}
